<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<?php
$arrContextOptions=array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);

$url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=1";
$xml = file_get_contents($url,false, stream_context_create($arrContextOptions));
$new = simplexml_load_string($xml);
$con = json_encode($new);
$data = json_decode($con, true);
?>

<div class="container mt-4">
    <h1 class="text-center my-4"><b>Tỉ giá tiền tệ Vietcombank ngày <?= $data['DateTime'] ?></b></h1>
    <table id="currencyTable" class="table table-hover" style="width:100%">
        <thead>
            <tr class="table-dark">
                <th>#</th>
                <th>Mã</th>
                <th>Biểu tượng</th>
                <th>Tên</th>
                <th>Giá mua</th>
                <th>Giá bán</th>
                <th>Giá chuyển nhượng</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data['Exrate'] as $k => $currency): ?>
                <tr>
                    <td><?= $k+1 ?></td>
                    <td><?= $currency['@attributes']['CurrencyCode'] ?></td>
                    <td>
                        <img src="https://flagcdn.com/48x36/<?= strtolower(substr($currency['@attributes']['CurrencyCode'], 0, -1)) ?>.png" style="height:24px;">
                    </td>
                    <td><?= $currency['@attributes']['CurrencyName'] ?></td>
                    <td><?= $currency['@attributes']['Buy'] ?></td>
                    <td><?= $currency['@attributes']['Sell'] ?></td>
                    <td><?= $currency['@attributes']['Transfer'] ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<link href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap5.min.css" rel="stylesheet">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

<script>
// $(document).ready(function() {
//     $('#currencyTable').DataTable({
//         "pagingType": "full_numbers", // Enable pagination buttons
//         "order": [[3, 'asc']], // Start without any sort order
//         "columnDefs": [{
//             "targets": 2, // Disable sorting on the flag column
//             "orderable": false
//         }]
//     });
// });

require([
    'https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js',
    'https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js' // Đường dẫn tới plugin DataTables
], function($){
    $(document).ready(function() {
        $('#currencyTable').DataTable({
            "pagingType": "full_numbers", // Enable pagination buttons
            "order": [[3, 'asc']], // Start without any sort order
            "columnDefs": [{
                "targets": 2, // Disable sorting on the flag column
                "orderable": false
            }]
        });
    });
});

</script>
